SW1:
  port: 32779
  hostname: 192.168.182.128
  groups:
    - nornir_labs
  data:
    tags:
      - ios 15
  connection_options:
    netmiko:
       extras:
         device_type: 'cisco_ios_telnet'
    napalm:
       extras:
         optional_args:
            transport: 'telnet'    
SW2:
  port: 32780
  hostname: 192.168.182.128
  groups:
    - nornir_labs
  data:
    tags:
      - ios 15
  connection_options:
    netmiko:
       extras:
         device_type: 'cisco_ios_telnet'
    napalm:
       extras:
         optional_args:
            transport: 'telnet'    
SW3:
  port: 32781
  hostname: 192.168.182.128
  groups:
    - nornir_labs
  data:
    tags:
      - ios 15
  connection_options:
    netmiko:
       extras:
         device_type: 'cisco_ios_telnet'
    napalm:
       extras:
         optional_args:
            transport: 'telnet'    
SW4:
  port: 32782
  hostname: 192.168.182.128
  groups:
    - nornir_labs
  data:
    tags:
      - ios 15
  connection_options:
    netmiko:
       extras:
         device_type: 'cisco_ios_telnet'
    napalm:
       extras:
         optional_args:
            transport: 'telnet'
